
name: test

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  push:
  workflow_dispatch:

jobs:
  test:

    runs-on: windows-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Check
      run: python foo.py
    - name: Label only
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      run: python -c "print('contains label')"
    
