
name: test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:

    runs-on: windows-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Check
      run: python foo.py
    
